"""
TestScript model.

Immutable validation test script generated by the Test Script Generator
for one RequirementVersion. ``version`` orders regenerations; rows are
never updated in place.
"""

from __future__ import annotations

from typing import TYPE_CHECKING
from uuid import UUID

from sqlalchemy import Enum as SAEnum
from sqlalchemy import ForeignKey, Index, Integer, String, Text
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.base_class import Base
from app.models.base_model import ImmutableBaseModel
from app.models.enums import TestScriptStatus
from app.models.mixins import non_empty_check

if TYPE_CHECKING:
    from app.models.assurance_decision import AssuranceDecision
    from app.models.prompt_version import PromptVersion
    from app.models.requirement_version import RequirementVersion


class TestScript(Base, ImmutableBaseModel):
    """
    Immutable generated validation script.

    Relationships:
        requirement_version: version under test (many -> 1).
        assurance_decision: verdict that required the script (many -> 1,
            nullable so scripts survive decision supersession).
        prompt_version: generator prompt snapshot used (many -> 1).
    """

    __tablename__ = "test_scripts"

    __table_args__ = (
        Index("ix_test_scripts_requirement_version_id", "requirement_version_id"),
        Index("ix_test_scripts_assurance_decision_id", "assurance_decision_id"),
        Index("ix_test_scripts_prompt_version_id", "prompt_version_id"),
        Index("ix_test_scripts_status", "status"),
        Index("ix_test_scripts_created_at", "created_at"),
        non_empty_check("script"),
    )

    # --- Identity ----------------------------------------------------

    requirement_version_id: Mapped[UUID] = mapped_column(
        ForeignKey("requirement_versions.id", ondelete="CASCADE"),
        nullable=False,
    )
    """Version under test; scripts die with their version."""

    assurance_decision_id: Mapped[UUID | None] = mapped_column(
        ForeignKey("assurance_decisions.id", ondelete="SET NULL"),
        nullable=True,
    )
    """
    Verdict that required the script. Nullable with ``SET NULL`` so the
    generated script (audit record) survives decision supersession.
    """

    prompt_version_id: Mapped[UUID] = mapped_column(
        ForeignKey("prompt_versions.id", ondelete="RESTRICT"),
        nullable=False,
    )
    """
    Generator prompt snapshot used. ``RESTRICT`` preserves
    reproducibility of every generated script.
    """

    # --- Content -------------------------------------------------------

    script: Mapped[str] = mapped_column(
        Text,
        nullable=False,
    )
    """Full generated validation script text (non-empty)."""

    status: Mapped[TestScriptStatus] = mapped_column(
        SAEnum(TestScriptStatus, name="test_script_status"),
        nullable=False,
        default=TestScriptStatus.DRAFT,
    )
    """Lifecycle status of the script."""

    version: Mapped[int] = mapped_column(
        Integer,
        nullable=False,
        default=1,
    )
    """Script revision number for this requirement version."""

    freshness: Mapped[str] = mapped_column(
        String(12), nullable=False, default="fresh",
        server_default="fresh", index=True,
    )
    """Traceability freshness: ``fresh`` | ``stale`` | ``superseded``."""

    origin: Mapped[str] = mapped_column(
        String(12), nullable=False, default="generated",
        server_default="generated", index=True,
    )
    """Test origin: ``generated`` | ``manual`` | ``imported``."""

    title: Mapped[str | None] = mapped_column(
        Text, nullable=True, default=None,
    )
    """Short human-readable title (manual/imported tests; generated ones
    may leave this NULL and fall back to a ``TS-<id>`` display code)."""

    external_code: Mapped[str | None] = mapped_column(
        String(64), nullable=True, default=None, index=True,
    )
    """External test-case code from a CSV import (matched on re-import)."""

    # --- Relationships ---------------------------------------------------

    requirement_version: Mapped[RequirementVersion] = relationship(
        back_populates="test_scripts",
    )
    """Version under test (many -> 1)."""

    assurance_decision: Mapped[AssuranceDecision | None] = relationship(
        back_populates="test_scripts",
    )
    """Verdict that required the script (many -> 1, nullable)."""

    prompt_version: Mapped[PromptVersion] = relationship(
        back_populates="test_scripts",
    )
    """Generator prompt snapshot used (many -> 1)."""
